# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c73418bdf8c6dc58ac0bbb00d4b394a3fb085df28d1804920d9aeceb6ac32296e624a72e86e382a979b778b87dd059484ed0f38bdb28629ef080dec594f3575

test:
  secret_key_base: 7495664c8bee83c84284f604fabd31945c36ac1d02e1c143d02c486dff29696a744065361620ae47750c8505d0eaeeb54effcfdc38c5567a3574a229a542a124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
